### ISSUE TITLE
Some stacks not marked as updateavailable altnought there is a new image

### ISSUE THREAD

**Issue by Twilek-de** [mbecker20/komodo#468]
With some stacks (it is always the same ones) Komodo does not fire an "Updateavailable" alert althought there is a new image available. In the container list this can be seen as the image only has a sha256 value

![Image](https://github.com/user-attachments/assets/4070a941-5cf6-4a23-a8e3-9380de88c75a)

After manual redeployment the right image tag will show up again. So Komodo has already pulled the information that there is a new image but doesn´t fire the alert (I have activated the pull new images option for the stack and my alerter fires for stackupdates for other stacks correctly)

![Image](https://github.com/user-attachments/assets/cea2193c-a29e-416d-943c-75151f3884c9)

**Comment by gcebollero** [comment]
Implement a new scheduled action than execute pull on the desired stacks. After the pull, the update notification is shown properly.

**Comment by Twilek-de** [comment]
I am not sure that I understand what you are saying. I think the new image is already pulled. Otherwise Komodo/Docker  wouldn´t know that the actual image does not have the "latest" tag anymore. What do you mean with implementing a scheduled action?

**Comment by kingp0dd** [comment]
this started to happen after the last 2 updates. Currently, all my stacks are not showing the update icon in the Stack list even if there are image updates available. 
I have to click the refresh button manually for it to show.

**Comment by kingp0dd** [comment]
> this started to happen after the last 2 updates. Currently, all my stacks are not showing the update icon in the Stack list even if there are image updates available. I have to click the refresh button manually for it to show.

seems to have been fixed in the latest release

**Comment by Twilek-de** [comment]
> > this started to happen after the last 2 updates. Currently, all my stacks are not showing the update icon in the Stack list even if there are image updates available. I have to click the refresh button manually for it to show.
> 
> seems to have been fixed in the latest release

Nice, I will keep my eyes open wether available updates are shown.

**Comment by Twilek-de** [comment]
I am still seeing updated stacks without notification

This triggered no Stackupdate Notification
![Image](https://github.com/user-attachments/assets/191c79b1-1ea8-491d-9fae-480ba8914278)

**Comment by kingp0dd** [comment]
Reporting back, I'm missing the update notification badges as well. I manually triggered one of my stacks, then suddenly the update badges of the other stacks started appearing. So I think it's not auto polling

**Comment by Twilek-de** [comment]
It is always the same stacks which do not trigger the update. Others reliably do. I have not found the common denominator of the ones which don´t work. One that never triggers is the image of searxng with the latest tag on docker.io.

**Comment by gcebollero** [comment]
> It is always the same stacks which do not trigger the update. Others reliably do. I have not found the common denominator of the ones which don´t work. One that never triggers is the image of searxng with the latest tag on docker.io.

I have been trying to determine why some stacks does not trigger the update... In my case, the update notification only works correctly if the container uses the 'latest' tag. If it is pinned to a particular version, the update notification never appears.
@Twilek-de can you check if you have the same behavior?

**Comment by Twilek-de** [comment]
> > It is always the same stacks which do not trigger the update. Others reliably do. I have not found the common denominator of the ones which don´t work. One that never triggers is the image of searxng with the latest tag on docker.io.
> 
> I have been trying to determine why some stacks does not trigger the update... In my case, the update notification only works correctly if the container uses the 'latest' tag. If it is pinned to a particular version, the update notification never appears. [@Twilek-de](https://github.com/Twilek-de) can you check if you have the same behavior?

I cannot confirm that. The SearXng container has the image with the "latest" tag, so that does not seem to be the deciding factor.

**Comment by kingp0dd** [comment]
I'm still getting the same issue for all my stacks.

**Comment by Twilek-de** [comment]
I think I found the problem. All stacks that didn´t work had an image path starting with docker.io/.... I removed that and the updates are recognized now.

**Comment by mbecker20** [comment]
@Twilek-de thanks for figuring out I was stumped, I wonder why docker.io/.. has issue while ghcr.io/.., gcr.io/.. and any other custom registry seems to work, will review

**Comment by Twilek-de** [comment]
docker.io also works, you just have to leave it out of the image path. Docker then automatically assumes it is docker hub and it works.

**Comment by mbecker20** [comment]
Yes I am aware, I never use `docker.io/..` just the image name, which is why I didn't notice the issue myself or recognize it from your description. I think this behavior of docker assuming `docker.io` is an edge case handled within docker code itself, possibly leading to auto update failure when it is specified, this is what I was going to review.

**Comment by mbecker20** [comment]
<img width="679" height="241" alt="Image" src="https://github.com/user-attachments/assets/6cb1f26a-92c8-49ef-a856-6a47b59b610f" />

I think this is it, even if you pull `docker.io/postgres:17`, the image is silently renamed to just `postgres`. This doesn't happen for eg `ghcr.io/...` image, and leads to Komodo not seeing the newer image.

**Comment by Twilek-de** [comment]
I have just removed the docker.io from all my stacks so for me the problem is gone. But I think it would be good if komodo could handle it, as a lot of ready made copy and past docker compose files from the web use it.

**Comment by teedoff087** [comment]
My stacks were updating automatically a couple of releases ago, but something in the last 2 updates caused this to stop working. I'm going to implement a Procedure to update them weekly, but ideally I would like this to work on its own like it was before.

**Comment by mbecker20** [comment]
@teedoff087 see https://komo.do/docs/resources/auto-update, it was mentioned in release notes with 🚨. But it's easy to set up and gives you a lot more easy control when to run global auto update. I also move to once a week updates and very happy with this.

**Comment by teedoff087** [comment]
> [@teedoff087](https://github.com/teedoff087) see https://komo.do/docs/resources/auto-update, it was mentioned in release notes with 🚨. But it's easy to set up and gives you a lot more easy control when to run global auto update. I also move to once a week updates and very happy with this.

Yeah, I've got it set up now and everything is working fine. I was just alarmed the updates stopped working. I should have read the release notes in detail, but it's hard to keep up with how fast the updates keep coming. Thank you!

**Comment by mbecker20** [comment]
Understood. I put the most important info like this at the very top of release notes with 🚨, if you glance at one part just check this.

**Comment by mbecker20** [comment]
The bug here is when user use images beginning with `docker.io`. When the image is pulled, Docker itself silently removes `docker.io/` from the image tag (`docker.io/postgres:17 -> postgres:17`), opening up edge case for this specific registry causing failure to recognize image update. It will work for users immediately if they remove `docker.io/` from images. Leaving this open for Komodo to close the edge case.

**Comment by kingp0dd** [comment]
> The bug here is when user use images beginning with `docker.io`. When the image is pulled, Docker itself silently removes `docker.io/` from the image tag (`docker.io/postgres:17 -> postgres:17`), opening up edge case for this specific registry causing failure to recognize image update. It will work for users immediately if they remove `docker.io/` from images. Leaving this open for Komodo to close the edge case.

I have compose that doesn't use that format but still have no update indicators. This happened only after updating to the 19.1

Are there logs i can look at to confirm or give more details about this?

**Comment by mbecker20** [comment]
@kingp0dd confirm you scheduled GlobalAutoUpdate as mentioned here https://komo.do/docs/resources/auto-update

**Comment by kingp0dd** [comment]
I'm sorry my bad. I missed the word new in the release notes. It's only
automatically installed on new 1.19

**Comment by kingp0dd** [comment]
sorry to reopen this. but i use the new method of Procedure to scan for updates:
```
[[procedure]]
name = "global update"
config.webhook_enabled = false
config.schedule_format = "Cron"
config.schedule = "0 0 5 * * *"
config.schedule_timezone = "Asia/Shanghai"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params = {}, enabled = true }
]
```

the procedure runs successfully as scheduled, but the Update icons are not showing again in Stack list:

<img width="768" height="690" alt="Image" src="https://github.com/user-attachments/assets/87719f52-4526-498b-93d4-b78faddab0c2" />


<img width="585" height="910" alt="Image" src="https://github.com/user-attachments/assets/af256403-fac5-4c1c-a85b-121be64c5412" />



which logs to check to confirm the issue?
