### ISSUE TITLE
[Bug] Failed to redeploy stack using webhook

### ISSUE THREAD

**Issue by vuongtlt13** [mbecker20/komodo#956]
### Description
When sending a GitLab webhook to redeploy a stack, the webhook handler rejects the request because the branch in the webhook payload (master) does not match the branch stored for the stack in the DB (main). The stack is linked to a repository whose branch is actually master, but the stack record shows main, causing the deploy to fail.

### Steps to reproduce

- Create a stack (id: 8347293847293847f) linked to a repository whose branch is **master**.
- Trigger the GitLab webhook for the stack: POST /listener/gitlab/stack/8347293847293847f/deploy (webhook branch/ref = master)

#### Observed behavior

- Webhook handling fails with this log/warning: 2025-11-03T06:02:15.938055Z WARN StackWebhook{id="8347293847293847f"}: core::listener::router: Failed at running webhook for stack 8347293847293847f | request branch does not match expected

- DB: stack 8347293847293847f has branch = main.

- The linked repo expects branch = master.

### Expected behavior

- The webhook should trigger a redeploy when the webhook branch/ref matches the repository branch.
- If the stack record is out-of-sync with the repository (for example due to a branch rename from master ⇄ main), Komodo should:
- Resolve and accept the repository’s current default branch when processing a webhook (and optionally update the stack record), or
- Return a clear error that includes both expected and received branch names and guidance to fix it, or
- Allow branch-aliasing/mappings (e.g., treat master and main as equivalents if configured).

### Root cause:
- Stack branch do not change when updated **linked_repo**

### Solution:
- Update logic updating stack with linked_repo and change git info (git_provider, branch, git_https)
- PR: https://github.com/moghtech/komodo/pull/957

#### Local test:
- Branch change from **main** to **master**  when updating linked_repo
- Before 
<img width="609" height="324" alt="Image" src="https://github.com/user-attachments/assets/fbf1e93b-8832-482e-9f58-de2b0122127f" />

- After

<img width="630" height="570" alt="Image" src="https://github.com/user-attachments/assets/8565595b-4e5b-481a-88b4-06874e11868a" />

**Comment by SergeyFilippov** [comment]
I have exactly the same issue... Webhooks are rejected, if the branch is not "main" (as it being reset in TOML on using Repo instead of direct git connection). 
So, to make web hooks work (and GitOps in general), one can't use Repos with non "main" branch. This is sad 😟.

**Comment by Delota** [comment]
I have the same with Github webhooks and using the build step.
This issue should get WAY more attention, it's such a core feature that just doesnt work...

I have a Repo->Build->Deploy. I put the webhook on the build step, and if the branch name is anything else then 'main', it throws the error.

```
WARN BuildWebhook{id=..."}: core::listener::router: Failed at running webhook for build ... | request branch does not match expected
```

**Comment by mbecker20** [comment]
@Delota the issue has been fixed for a while and available in the 2.0.0-dev releases

**Comment by Delota** [comment]
Ok thanks, very glad to hear that! New to Komodo so wasnt aware it was already fixed, got here by searching the error. I'll switch my build over

**Comment by SergeyFilippov** [comment]
> [@Delota](https://github.com/Delota) the issue has been fixed for a while and available in the 2.0.0-dev releases

@mbecker20 Thanks for a great app, very useful and flexible. 
I've tried to find info in readme or docs, but nowhere it describes the current situation with `v1 vs v2`.
So, just to make things clear:
1. Is v1 not supported anymore and none of the bugs there will be fixed?
2. If v2-dev is the solution, can it be expected not to break on every release? (sorry, this is how I personally read "dev" prefixes/suffixes)

**Comment by cryocaustik** [comment]
> > [@Delota](https://github.com/Delota) the issue has been fixed for a while and available in the 2.0.0-dev releases
> 
> [@mbecker20](https://github.com/mbecker20) Thanks for a great app, very useful and flexible. I've tried to find info in readme or docs, but nowhere it describes the current situation with `v1 vs v2`. So, just to make things clear:
> 
>     1. Is v1 not supported anymore and none of the bugs there will be fixed?
> 
>     2. If v2-dev is the solution, can it be expected not to break on every release? (sorry, this is how I personally read "dev" prefixes/suffixes)

Came back to this issue after having encountered it in October 2025 and was surprised the issue was not yet resolved after the discord discussions seemed to indicate it was an easy fix. 

Would also like to get clarification if we can expect to see a fix for this in v1.* given v2 is not stable yet and #957  was closed citing v2 fix. 

In the meantime, for anyone else who might find this issue from search: you can bandaid fix this by using `mongosh` (or similar app to connect to the mongo db used by komdo) and executing an update to the stack config:
```
db.Stack.updateOne(
  { name: "<stack-name>" },
  { $set: { "config.branch": "<correct branch name>" } }
)
```
